export const orders = [
  {
    id: 1,
    client: "MARIO",
    amount: 550.0,
    data_entrega: "pendente",
    status: "pendente",
    items: [
      {
        id: 1,
        description: "HD 500GB SAMSUNG DESK",
        brand: "SAMSUNG",
        price: 10.0,
        quantity: 3,
      },
      {
        id: 12,
        description: "HD 2TB SEAGATE DESK",
        brand: "SEAGATE",
        price: 40.0,
        quantity: 8,
      },
      {
        id: 17,
        description: "HD 1TB WD DESK",
        brand: "WESTERN DIGITAL",
        price: 20.0,
        quantity: 10,
      },
      {
        id: 17,
        description: "HD 1TB WD DESK",
        brand: "WESTERN DIGITAL",
        price: 20.0,
        quantity: 60,
      },
    ],
  },
  {
    id: 2,
    client: "DIRCEU",
    amount: 550.0,
    data_entrega: "30/07/2024",
    status: "PAGO",
    items: [
      {
        id: 1,
        description: "HD 500GB SAMSUNG DESK",
        brand: "SAMSUNG",
        price: 10.0,
        quantity: 3,
      },
      {
        id: 12,
        description: "HD 2TB SEAGATE DESK",
        brand: "SEAGATE",
        price: 40.0,
        quantity: 8,
      },
      {
        id: 17,
        description: "HD 1TB WD DESK",
        brand: "WESTERN DIGITAL",
        price: 20.0,
        quantity: 10,
      },
      {
        id: 17,
        description: "HD 1TB WD DESK",
        brand: "WESTERN DIGITAL",
        price: 20.0,
        quantity: 10,
      },
    ],
  },
  {
    id: 3,
    client: "MARIO",
    amount: 550.0,
    data_entrega: "pendente",
    status: "pendente",
    items: [
      {
        id: 1,
        description: "HD 500GB SAMSUNG DESK",
        brand: "SAMSUNG",
        price: 10.0,
        quantity: 19,
      },
      {
        id: 12,
        description: "HD 2TB SEAGATE DESK",
        brand: "SEAGATE",
        price: 40.0,
        quantity: 12,
      },
      {
        id: 17,
        description: "HD 1TB WD DESK",
        brand: "WESTERN DIGITAL",
        price: 20.0,
        quantity: 25,
      },
      {
        id: 17,
        description: "HD 1TB WD DESK",
        brand: "WESTERN DIGITAL",
        price: 20.0,
        quantity: 60,
      },
    ],
  },
];
