export const products = [
    {
        id:1,
        description:"HD 500GB SAMSUNG DESK",
        brand: "SAMSUNG",
        price: 10.0,
    },
    {
        id:2,
        description:"HD 750GB SAMSUNG DESK",
        brand: "SAMSUNG",
        price: 10.0,
    },
    {
        id:3,
        description:"HD 1TB SAMSUNG DESK",
        brand: "SAMSUNG",
        price: 20.0,
    },
    {
        id:4,
        description:"HD 1.5TB SAMSUNG DESK",
        brand: "SAMSUNG",
        price: 40.0,
    },
    {
        id:5,
        description:"HD 2TB SAMSUNG DESK",
        brand: "SAMSUNG",
        price: 40.0,
    },
    {
        id:6,
        description:"HD 3TB SAMSUNG DESK",
        brand: "SAMSUNG",
        price: 40.0,
    },
    {
        id:7,
        description:"HD 4TB SAMSUNG DESK",
        brand: "SAMSUNG",
        price: 40.0,
    },
    {
        id:8,
        description:"HD 500GB SEAGATE DESK",
        brand: "SEAGATE",
        price: 10.0,
    },
    {
        id:9,
        description:"HD 750GB SEAGATE DESK",
        brand: "SEAGATE",
        price: 10.0,
    },
    {
        id:10,
        description:"HD 1TB SEAGATE DESK",
        brand: "SEAGATE",
        price: 20.0,
    },
    {
        id:11,
        description:"HD 1.5TB SEAGATE DESK",
        brand: "SEAGATE",
        price: 40.0,
    },
    {
        id:12,
        description:"HD 2TB SEAGATE DESK",
        brand: "SEAGATE",
        price: 40.0,
    },
    {
        id:13,
        description:"HD 3TB SEAGATE DESK",
        brand: "SEAGATE",
        price: 40.0,
    },
    {
        id:14,
        description:"HD 4TB SEAGATE DESK",
        brand: "SEAGATE",
        price: 40.0,
    },
    {
        id:15,
        description:"HD 500GB WD DESK",
        brand: "WESTERN DIGITAL",
        price: 10.0,
    },
    {
        id:16,
        description:"HD 750GB WD DESK",
        brand: "WESTERN DIGITAL",
        price: 10.0,
    },
    {
        id:17,
        description:"HD 1TB WD DESK",
        brand: "WESTERN DIGITAL",
        price: 20.0,
    },
    {
        id:18,
        description:"HD 1.5TB WD DESK",
        brand: "WESTERN DIGITAL",
        price: 40.0,
    },
    {
        id:19,
        description:"HD 2TB WD DESK",
        brand: "WESTERN DIGITAL",
        price: 40.0,
    },
    {
        id:20,
        description:"HD 3TB WD DESK",
        brand: "WESTERN DIGITAL",
        price: 40.0,
    },
    {
        id:21,
        description:"HD 4TB WD DESK",
        brand: "WESTERN DIGITAL",
        price: 40.0,
    },
    {
        id:22,
        description:"HD 500GB HITACHI DESK",
        brand: "HITACHI",
        price: 10.0,
    },
    {
        id:23,
        description:"HD 750GB HITACHI DESK",
        brand: "HITACHI",
        price: 10.0,
    },
    {
        id:24,
        description:"HD 1TB HITACHI DESK",
        brand: "HITACHI",
        price: 20.0,
    },
    {
        id:25,
        description:"HD 1.5TB HITACHI DESK",
        brand: "HITACHI",
        price: 40.0,
    },
    {
        id:26,
        description:"HD 2TB HITACHI DESK",
        brand: "HITACHI",
        price: 40.0,
    },
    {
        id:27,
        description:"HD 3TB HITACHI DESK",
        brand: "HITACHI",
        price: 40.0,
    },
    {
        id:28,
        description:"HD 4TB HITACHI DESK",
        brand: "HITACHI",
        price: 40.0,
    },
]